name: Sync to Hugging Face Spaces
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Cria uma pasta temporária só para o deploy externo
          mkdir ../deploy_hf
          
          # 2. Copia o Dockerfile e o conteúdo da pasta my-cms para lá
          cp Dockerfile ../deploy_hf/
          cp -r my-cms/* ../deploy_hf/
          
          # 3. Entra na pasta temporária e inicializa um Git limpo
          cd ../deploy_hf
          git init -b main
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # 4. Adiciona e envia apenas esses arquivos para o Hugging Face
          git add .
          git commit -m "deploy: atualizando backend sem arquivos pesados"
          git push --force https://AnnaBia22:$HF_TOKEN@huggingface.co/spaces/AnnaBia22/backend-sem-parar main